spring.application.name=hackathon-management
spring.datasource.url=jdbc:mysql://localhost:3306/hackathon_db
spring.datasource.username=root
spring.datasource.password=7777

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true